name: Deploy static pages to prod
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy-prod:
    if: github.repository_owner == 'ParkingReformNetwork'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci

      - name: Generate data set
        run: npm run gen-data-set
      - name: Copy data set zip to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRN_FTP_HOST }}
          username: ${{ secrets.PRN_SERVER_USERNAME }}
          key: ${{ secrets.PRN_SERVER_PRIVATE_KEY }}
          source: data/generated/mandates-map-data.zip
          target: /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/data
          strip_components: 2

      - name: Generate HTML pages
        run: npm run gen-html
      - name: Generate redirects
        run: npm run gen-redirects
      - name: Archive city_detail/ contents
        run: |
          cd city_detail
          tar -czf ../city_details.tar.gz .
      - name: Copy city_detail/ to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PRN_FTP_HOST }}
          username: ${{ secrets.PRN_SERVER_USERNAME }}
          key: ${{ secrets.PRN_SERVER_PRIVATE_KEY }}
          source: city_details.tar.gz
          target: /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/city_detail
      - name: Extract city_detail/ on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRN_FTP_HOST }}
          username: ${{ secrets.PRN_SERVER_USERNAME }}
          key: ${{ secrets.PRN_SERVER_PRIVATE_KEY }}
          script: |
            mkdir -p /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/details-tmp
            tar -xzf \
              /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/city_detail/city_details.tar.gz \
              -C /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/details-tmp

            rsync --archive --verbose --delete --no-times \
              /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/details-tmp \
              /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/city_detail/

            rm -rf /var/www/${{ secrets.PRN_SERVER_HOST }}/mandates-map/details-tmp
