name: Tests
on: [pull_request, workflow_dispatch]
jobs:
  test:
    if: github.repository_owner == 'ParkingReformNetwork'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Enable corepack
        run: corepack enable
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm exec playwright install --with-deps

      - run: pnpm check
      - run: pnpm lint
      - run: pnpm test

      - name: Check static generation works
        run: |
          pnpm gen-html
          pnpm gen-redirects
          pnpm gen-data-set
